# Generated by Django 5.0.6 on 2024-05-27 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_depart', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NiveisAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rotinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_rotina', models.CharField(max_length=255)),
                ('nivel_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.niveisacesso')),
            ],
        ),
        migrations.CreateModel(
            name='Tabelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subtabela', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revisor', models.IntegerField()),
                ('nome_revisor', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.IntegerField()),
                ('password_hash', models.TextField()),
                ('nivel_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.niveisacesso')),
            ],
        ),
        migrations.CreateModel(
            name='EtapasAprovacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subtabela', models.CharField(max_length=255)),
                ('status_aprovacao', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('departamento_destino', models.IntegerField()),
                ('descricao', models.TextField()),
                ('revisor', models.IntegerField()),
                ('nome_revisor', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_db.departamentos')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_db.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.departamentos')),
                ('nivel_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.niveisacesso')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.rotinas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.usuarios')),
            ],
        ),
    ]
