# Generated by Django 5.0.6 on 2024-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0002_alter_usuarios_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password_hash',
            field=models.TextField(),
        ),
    ]
